# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib pnglitchr, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_pnglitchr__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_pnglitchr__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Apply filter
#'
#' @param bytes PNG image data
#' @param filter_type Filter type. 0: None, 1: Sub, 2: Up, 3: Average, 4: Paeth
#' @param from Scan line index
#' @param lines Number of scan lines to be updated
#' @returns PNG image data
#' @noRd
`pgltc_apply_filter` <- function(`bytes`, `filter_type`, `from`, `lines`) {
  .Call(savvy_pgltc_apply_filter__impl, `bytes`, `filter_type`, `from`, `lines`)
}

#' Count scanlines
#'
#' @param bytes PNG image data
#' @returns Total number of scanlines
#' @noRd
`pgltc_count_scanlines` <- function(`bytes`) {
  .Call(savvy_pgltc_count_scanlines__impl, `bytes`)
}

#' Random copy
#'
#' @param bytes PNG image data
#' @param times Number of times to copy
#' @returns PNG image data
#' @noRd
`pgltc_random_copy` <- function(`bytes`, `times`) {
  .Call(savvy_pgltc_random_copy__impl, `bytes`, `times`)
}

#' Remove filters
#'
#' @param bytes PNG image data
#' @param from Scan line index
#' @param lines Number of scan lines to be updated
#' @returns PNG image data
#' @noRd
`pgltc_remove_filter` <- function(`bytes`, `from`, `lines`) {
  .Call(savvy_pgltc_remove_filter__impl, `bytes`, `from`, `lines`)
}

#' Transpose
#'
#' @param bytes PNG image data
#' @param src Scan line index
#' @param dst Scan line index
#' @param lines Number of scan lines to be updated
#' @returns PNG image data
#' @noRd
`pgltc_transpose` <- function(`bytes`, `src`, `dst`, `lines`) {
  .Call(savvy_pgltc_transpose__impl, `bytes`, `src`, `dst`, `lines`)
}


